#!/usr/bin/python

import glob
import os
import subprocess

current_working_dir = os.getcwd()
assertion_message =  "This is dangerous to run anywhere. " \
    "DO this in the special directory mentioned here"
assert "/code-reviews" in current_working_dir, assertion_message
paths = glob.glob('*/')
print "folders are %s" % paths

for path in paths:
    print "-" * 40
    print "SWITCHING TO %s" % path
    os.chdir(os.path.abspath(path))
    find_unreviewed = os.path.expanduser("~/.git-monitor/find_unreviewed")
    subprocess.call(["git", "pull"])
    subprocess.call([find_unreviewed])
    os.chdir("..")
